default: &default
  address:              smtp.mandrillapp.com
  port:                 587
  domain:               herokuapp.com
  user_name:            app16876859@heroku.com
  password:             mt-3Dm2y9Mrpm-LUVQvJDw
  authentication:       login
  enable_starttls_auto: true

development:
  <<: *default

production:
  <<: *default