default: &default
  address:              smtp.mandrillapp.com
  port:                 587
  domain:               spiderid.co
  user_name:            app16876859@heroku.com
  password:             Aq1yHCreRD8JetUvA3RAZw
  authentication:       login
  enable_starttls_auto: true

development:
  <<: *default

production:
  <<: *default